routes/web.php
<?php

Route::group(['namespace' => 'Users'], function(){
	Route::get('/','HomeController@index');
	Route::get('/post/{post}','postController@post')->name('post');
	Route::get('post/tag/{tag}','HomeController@tags')->name('tag');
	Route::get('post/category/{category}','HomeController@category');
});


Route::group(['namespace' => 'Admin'], function(){
	
	Route::get('admin/home','HomeController@index')->name('admin/home');

	Route::resource('admin/post','PostController');

	Route::resource('admin/tag','TagController');

	Route::resource('admin/category','CategoryController');

	Route::resource('admin/user','UserController');
	
	Route::resource('admin/role','RoleController');


	Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');

	Route::post('admin/login', 'Auth\LoginController@login');

	Route::get('admin/logout','Auth\LoginController@logout')->name('admin.logout');


});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\Category;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
    {
        $this->middleware('auth:admin');
    }
    
    public function index()
    {
         $categoryData = Category::get();
        return view('admin.category.show')->with('categoryData', $categoryData);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([

            'categoryname'=> 'required',
            'catslug'=> 'required'
        ]);

        $input = [
            'name' => $request->categoryname,
            'slug' => $request->catslug
        ];

        Category::create($input);
        return redirect('admin/category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $allCategoryData =  Category::where('id', $id)->first();

       return view('admin.category.edit')->with('data', $allCategoryData);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([

            'categoryname'=> 'required',
            'catslug'=> 'required'
        ]);

        $input = [
            'name' => $request->categoryname,
            'slug' => $request->catslug
        ];

        Category::where('id', $id)->update($input);
        return redirect('admin/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::where('id',$id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/category/category.blade.php
@extends('admin.layouts.app')

@section('main_content')
<div class="content-wrapper">
<section class="content">
<div class="row">
  <h1 style="margin-left: 15px;">Create Your Category</h1>
   @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <h5>{{ $error }}</h5>
                  @endforeach
              </ul>
          </div>
      @endif
<form role="form"  action="{{route('category.store')}}" method="post">
  {{csrf_field()}}
<div class="col-offset-3 col-lg-6">
  <div class="box box-primary ">
              <div class="box-body">
               <div class="form-group">
                  <label for="categoryname">Name</label>
                  <input type="text" class="form-control" id="categoryname" name="categoryname" placeholder="Category Tag">
                </div>

                 <div class="form-group">
                  <label for="catslug">Post Slug</label>
                  <input type="text" class="form-control" id="catslug" name="catslug" placeholder="Category Slug">
                </div>
               <button type="submit" class="btn btn-primary">Submit</button>
               <a class="btn btn-warning" href="{{route('category.index')}}">Back</a>

            </div>
    </div>
</div>
 </form>
 </div>
</section>
</div>
  
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.app')

@section('main_content')
<div class="content-wrapper">
<section class="content">
<div class="row">
  <h1 style="margin-left: 15px;">Create Your Category</h1>
   @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <h5>{{ $error }}</h5>
                  @endforeach
              </ul>
          </div>
      @endif
<form role="form"  action="{{route('category.update',$data->id)}}" method="post">
  {{csrf_field()}}
  {{method_field('PUT')}}
<div class="col-offset-3 col-lg-6">
  <div class="box box-primary ">
              <div class="box-body">
               <div class="form-group">
                  <label for="categoryname">Name</label>
                  <input type="text" class="form-control" id="categoryname" name="categoryname" value="{{$data->name}}">
                </div>

                 <div class="form-group">
                  <label for="catslug">Post Slug</label>
                  <input type="text" class="form-control" id="catslug" name="catslug" value="{{$data->slug}}">
                </div>
               <button type="submit" class="btn btn-primary">Submit</button>
               <a class="btn btn-warning" href="{{route('category.index')}}">Back</a>

            </div>
    </div>
</div>
 </form>
 </div>
</section>
</div>
  
@endsection

resources/views/admin/category/show.blade.php
@extends('admin.layouts.app')

@section('main_content')
			  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Blank page
        <small>it all starts here</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Title</h3>

          <a href="{{route('category.create')}}" class=" col-lg-offset-5 btn btn-success">Create New</a>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
          </div>
        </div>
        <div class="box-body">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Serial</th>
                  <th>Name</th>
                  <th>Slug(s)</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categoryData as $key => $data)
                
                <tr>
                  <td>{{$key}}</td>
                  <td>{{$data->name}}</td> 
                  <td>{{$data->slug}}</td> 
                  <td><a href="{{route('category.edit',$data->id)}}"><span class="glyphicon glyphicon-edit"></span></a></td>
                  <td>
                     <form action="{{route('category.destroy',$data->id)}}" method="post" id="delete_form_{{$data->id}}" style="display: none">
                      {{csrf_field()}}
                      {{method_field('DELETE')}}
                     </form>
                     <a href="" onclick="

                      if(confirm('Are sure to delete?'))
                      {
                        event.preventDefault();
                        document.getElementById('delete_form_{{$data->id}}').submit();
                      }
                      else{
                        event.preventDefault();
                      }
                     ">
                        <span class="glyphicon glyphicon-trash"></span></a>
                    </a>
                  </td>
                  </tr>
                  @endforeach
                
                </tbody>
                <tfoot>
                <tr>
                  <th>Serial</th>
                  <th>Name</th>
                  <th>Slug(s)</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection