routes/web.php
<?php

Route::group(['namespace' => 'Users'], function(){
	Route::get('/','HomeController@index');
	Route::get('/post/{post}','postController@post')->name('post');
	Route::get('post/tag/{tag}','HomeController@tags')->name('tag');
	Route::get('post/category/{category}','HomeController@category');
});


Route::group(['namespace' => 'Admin'], function(){
	
	Route::get('admin/home','HomeController@index')->name('admin/home');

	Route::resource('admin/post','PostController');

	Route::resource('admin/tag','TagController');

	Route::resource('admin/category','CategoryController');

	Route::resource('admin/user','UserController');
	
	Route::resource('admin/role','RoleController');


	Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');

	Route::post('admin/login', 'Auth\LoginController@login');

	Route::get('admin/logout','Auth\LoginController@logout')->name('admin.logout');


});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\Post;
use App\Model\user\Tag;
use App\Model\user\Category;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
    {
        $this->middleware('auth:admin');
    }
   
    public function index()
    {
        $postData = Post::get();
        return view('admin.post.show')->with('postData', $postData);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::get();

        $categories = Category::get();

        return view('admin.post.post')->with(compact('tags','categories'));
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([

            'posttitle' => 'required',
            'postsubtitle'=> 'required',
            'postslug'=> 'required',
            'image'=> 'required|mimes:jpeg,jpg,bmp,png|max:7120',
            'body'=> 'required',
            'posttag' => 'required',
            'postcategory' => 'required'
        ]);

        // $input = [

        //     'title' => $request->posttitle,
        //     'subtitle' => $request->postsubtitle,
        //     'slug' => $request->postslug,
        //     'body' => $request->body,
        //     'image' => $request->image
        // ];
        // $post->create($input);
        // $post->tags()->sync($request->posttag)->create();
        // $post->categories()->sync($request->postcategory)->create();

        if($request->hasFile('image'))
        {
            $imageName = $request->image->store('public');
        }
        $post = new Post;
        $post->image = $imageName;
        $post->title=$request->posttitle;
        $post->subtitle=$request->postsubtitle;
        $post->slug=$request->postslug;
        $post->body=$request->body;
        $post->status=$request->status;
        $post->save();
        $post->tags()->sync($request->posttag);
        $post->categories()->sync($request->postcategory);


        return redirect('admin/post');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $tags = Tag::get();
        $categories = Category::get();
        $data =  Post::with('tags','categories')->where('id', $id)->first();


        return view('admin.post.edit')->with(compact('tags','categories','data'));
       

       return view('admin.post.edit')->with('data', $allpostyData);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $request->validate([

            'posttitle' => 'required',
            'postsubtitle'=> 'required',
            'postslug'=> 'required',
            'body'=> 'required',
            'posttag' => 'required',
            'postcategory' => 'required',
            'image'=> 'required|mimes:jpeg,jpg,bmp,png|max:7120',

        ]);

       /* $input = [

            'title' => $request->posttitle,
            'subtitle' => $request->postsubtitle,
            'slug' => $request->postslug,
            'body' => $request->body,
            'image' => $request->image,
            'status' =>$request->status
        ];*/
         // Post::where('id', $id)->update($input);

        if($request->hasFile('image'))
        {
            $imageName = $request->image->store('public');
        }

        $post = Post::find($id);
       
        $post->title = $request->posttitle;
        $post->subtitle = $request->postsubtitle;
        $post->slug = $request->postslug;
        $post->body = $request->body;
        $post->image = $imageName;
        $post->status = $request->status;
        $post->save();

        $post->tags()->sync($request->posttag);
        $post->categories()->sync($request->postcategory);

        // Tag::create($tags);
        // Category::create($category);

       
        return redirect('admin/post');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        post::where('id',$id)->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Users/PostController.php
<?php

namespace App\Http\Controllers\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\user\Post;

class PostController extends Controller
{
     public function post(Post $post)
   {

   		return view('user.post')->with('posts',$post);
   }
}

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')

@section('main_content')
<div class="content-wrapper">
<section class="content">
<div class="row">
	<h1 style="margin-left: 15px;">Update Your Post</h1>
  @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <h3>{{ $error }}</h3>
                  @endforeach
              </ul>
          </div>
      @endif
<form role="form" method="post" action="{{route('post.update',$data->id)}}" enctype="multipart/form-data">
  {{csrf_field()}}
    {{method_field('PUT')}}
<div class="col-lg-6">
	<div class="box box-primary">
              <div class="box-body">
                <div class="form-group">
                  <label for="posttitle">Post Title</label>
                  <input type="text" class="form-control" id="posttitle" name="posttitle" value="{{$data->title}}">
                </div>

                <div class="form-group">
                  <label for="postsubtitle">Post Subtitle</label>
                  <input type="text" class="form-control" id="postsubtitle" name="postsubtitle" value="{{$data->subtitle}}">
                </div>
                 <div class="form-group">
                  <label for="postslug">Post Slug</label>
                  <input type="text" class="form-control" id="postslug" name="postslug" value="{{$data->slug}}">
                </div>

           
            </div>
  	</div>
</div>
<div class="col-lg-6">
	<div class="box box-primary">
            <div class="box-header with-border">
              <div class="pull-right">
                  <div class="form-group">
                  <label for="image">Images</label>
                    <input type="file" id="image" name="image">
                </div>
              </div>
	 		
              <div class="pull-left">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" value="1" name="status"
                     @if($data->status == '1')
                     checked = "checked"
                      @endif >publish
                  </label>
                </div>
              </div>
      </br>
      </br>
           <div class="form-group" style="margin-top: 18px">
                <label>Post Tag</label>
                <select class="form-control select2 select2-hidden-accessible" multiple="" data-placeholder="Select a State" name="posttag[]" style="width: 100%;" tabindex="-1" aria-hidden="true">
                   @foreach($tags as $tag)  
                  <option value="{{$tag->id}}"

                  @foreach($data->tags as $postdata)
                    @if($postdata->id == $tag->id)
                      selected
                      @endif
                  @endforeach
                    >{{$tag->name}}</option>
                @endforeach
                </select>
              </div>

               <div class="form-group" style="margin-top: 18px">
                <label>Post Category</label>
                <select class="form-control select2 select2-hidden-accessible" multiple="" data-placeholder="Select a State" name="postcategory[]" style="width: 100%;" tabindex="-1" aria-hidden="true">
                @foreach($categories as $category)  
                  <option value="{{$category->id}}"

                  @foreach($data->categories as $postcategories)
                    @if($postcategories->id == $category->id)
                      selected
                      @endif
                  @endforeach

                    >{{$category->name}}</option>
                @endforeach
                </select>
              </div>

            </div>
      </div>
 </div>
<div class="col-md-12">
     	  <div class="box">
         <div class="box-body pad">
          <label for="body">Post</label>
                <textarea  id="editor1"  name="body" 
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"> {{$data->body}}
                          	
                 </textarea> 
          <button type="submit" class="btn btn-primary">Submit</button>
           <a class="btn btn-warning" href="{{route('post.index')}}">Back</a>

            </div>
          </div>
    </div>
 </form>
 </div>
</section>
</div>
  
@endsection

resources/views/admin/post/post.blade.php
@extends('admin.layouts.app')

@section('main_content')
<div class="content-wrapper">
<section class="content">
<div class="row">
	<h1 style="margin-left: 15px;">Create Your Post</h1>
  @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <h3>{{ $error }}</h3>
                  @endforeach
              </ul>
          </div>
      @endif
<form role="form" method="post" action="{{route('post.store')}}" enctype="multipart/form-data">
  {{csrf_field()}}
<div class="col-lg-6">
	<div class="box box-primary">
              <div class="box-body">
                <div class="form-group">
                  <label for="posttitle">Post Title</label>
                  <input type="text" class="form-control" id="posttitle" name="posttitle" placeholder="Post title">
                </div>

                <div class="form-group">
                  <label for="postsubtitle">Post Subtitle</label>
                  <input type="text" class="form-control" id="postsubtitle" name="postsubtitle" placeholder="Post Tag">
                </div>
                 <div class="form-group">
                  <label for="postslug">Post Slug</label>
                  <input type="text" class="form-control" id="postslug" name="postslug" placeholder="Post Slug">
                </div>
            </div>
  	</div>
</div>
<div class="col-lg-6">
  <div class="box box-primary">
            <div class="box-header with-border">
              <div class="pull-right">
                  <div class="form-group">
                  <label for="image">Images</label>
                    <input type="file" id="image" name="image">
                </div>
              </div>
      
              <div class="pull-left">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" name="status" value="1" /> publish
                  </label>
                </div>
              </div>
      </br>
      </br>
           <div class="form-group" style="margin-top: 18px">
                <label>Post Tag</label>
                <select class="form-control select2 select2-hidden-accessible" multiple="" data-placeholder="Select a State" name="posttag[]" style="width: 100%;" tabindex="-1" aria-hidden="true">
                
                @foreach($tags as $tag)  
                  <option value="{{$tag->id}}">{{$tag->name}}</option>
                @endforeach
                </select>
              </div>

               <div class="form-group" style="margin-top: 18px">
                <label>Post Category</label>
                <select class="form-control select2 select2-hidden-accessible" multiple="" data-placeholder="Select a State" name="postcategory[]" style="width: 100%;" tabindex="-1" aria-hidden="true">
                  @foreach($categories as $category)  
                  <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
                </select>
              </div>

            </div>
      </div>
 </div>
<div class="col-md-12">
     	  <div class="box">
         <div class="box-body pad">
          <label for="body">Post</label>
                <textarea  id="editor1" placeholder="write post here......" name="body" 
                          style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                          	
                 </textarea> 
          <button type="submit" class="btn btn-primary">Submit</button>
           <a class="btn btn-warning" href="{{route('post.index')}}">Back</a>

            </div>
          </div>
    </div>
 </form>
 </div>
</section>
</div>
  
@endsection

resources/views/admin/post/show.blade.php
@extends('admin.layouts.app')

@section('main_content')
			  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Blank page
        <small>it all starts here</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Title</h3>
          <a href="{{route('post.create')}}" class=" col-lg-offset-5 btn btn-success">Create New</a>


          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
          </div>
        </div>
         <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Serial No</th>
                  <th>Title</th>
                  <th>Subtitle</th>
                  <th>Slug</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>

                  @foreach($postData as $key => $data)
                <tr>
                  <td>{{$key}}</td>
                  <td>{{$data->title}}</td>
                  <td>{{$data->subtitle}}</td>
                  <td>{{$data->slug}}</td>
                  <td>{{$data->image}}</td>
                  <td>

                   <a href="{{route('post.edit',$data->id)}}"><span class="glyphicon glyphicon-edit"></span></a> || 

                   <form action="{{route('post.destroy',$data->id)}}" method="post" id="delete_form_{{$data->id}}" style="display: none">
                      {{csrf_field()}}
                      {{method_field('DELETE')}}
                     </form>
                     <a href="" onclick="

                      if(confirm('Are sure to delete?'))
                      {
                        event.preventDefault();
                        document.getElementById('delete_form_{{$data->id}}').submit();
                      }
                      else{
                        event.preventDefault();
                      }
                     ">
                        <span class="glyphicon glyphicon-trash"></span></a>
                    </a>
                   </td>
                  </tr>
                 @endforeach 

                </tbody>
                <tfoot>
                <tr>
                  <th>Serial No</th>
                  <th>Title</th>
                  <th>Subtitle</th>
                  <th>Slug</th>
                  <th>Body</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        <!-- /.box-body -->
        <div class="box-footer">
          Footer
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection